# 1 "data/maps/RustboroCity_Flat1_1F/scripts.pory"

# 2 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
RustboroCity_Flat1_1F_MapScripts::
# 3 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
	.byte 0
# 4 "data/maps/RustboroCity_Flat1_1F/scripts.pory"

# 5 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
RustboroCity_Flat1_1F_EventScript_Man::
# 6 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
	msgbox RustboroCity_Flat1_1F_Text_EveryPokemonHasAbility, MSGBOX_NPC
# 7 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
	end
# 8 "data/maps/RustboroCity_Flat1_1F/scripts.pory"

# 9 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
RustboroCity_Flat1_1F_EventScript_Woman::
# 10 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
	msgbox RustboroCity_Flat1_1F_Text_PokemonStrange, MSGBOX_NPC
# 11 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
	end
# 12 "data/maps/RustboroCity_Flat1_1F/scripts.pory"

# 13 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
RustboroCity_Flat1_1F_Text_EveryPokemonHasAbility:
# 14 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
	.string "Cada Pokémon tiene una habildad.$"
# 15 "data/maps/RustboroCity_Flat1_1F/scripts.pory"

# 16 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
RustboroCity_Flat1_1F_Text_PokemonStrange:
# 17 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
	.string "Mi esposo dice cosas tan obvias que me\nhace querer divorciarme.\pPero es más barato vivir\ncon dos sueldos.$"
