RustboroCity_House2_MapScripts::
	.byte 0

RustboroCity_House2_EventScript_PokefanF::
	msgbox RustboroCity_House2_Text_TrainerSchoolExcellent, MSGBOX_NPC
	end

RustboroCity_House2_EventScript_LittleGirl::
	msgbox RustboroCity_House2_Text_RoxanneKnowsALot, MSGBOX_NPC
	end

RustboroCity_House2_Text_TrainerSchoolExcellent:
	.string "La Escuela de Entrenadores es excelente,\n¡Incluso podrían salir Líderes\lde Gimnasio de ahí!$"

RustboroCity_House2_Text_RoxanneKnowsALot:
	.string "¡Roxanne es genial!$"
