# 1 "data/maps/MagmaHideout_2F_1R/scripts.pory"

# 2 "data/maps/MagmaHideout_2F_1R/scripts.pory"
MagmaHideout_2F_1R_MapScripts::
# 3 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.byte 0
# 4 "data/maps/MagmaHideout_2F_1R/scripts.pory"

# 5 "data/maps/MagmaHideout_2F_1R/scripts.pory"
MagmaHideout_2F_1R_EventScript_Grunt14::
# 6 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	trainerbattle_single TRAINER_GRUNT_MAGMA_HIDEOUT_14, MagmaHideout_2F_1R_Text_Grunt14Intro, MagmaHideout_2F_1R_Text_Grunt14Defeat
# 7 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	msgbox MagmaHideout_2F_1R_Text_Grunt14PostBattle, MSGBOX_AUTOCLOSE
# 8 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	end
# 9 "data/maps/MagmaHideout_2F_1R/scripts.pory"

# 10 "data/maps/MagmaHideout_2F_1R/scripts.pory"
MagmaHideout_2F_1R_EventScript_Grunt3::
# 11 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	msgbox MagmaHideout_2F_1R_Text_Grunt3PostBattle, MSGBOX_AUTOCLOSE
# 12 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	end
# 13 "data/maps/MagmaHideout_2F_1R/scripts.pory"

# 14 "data/maps/MagmaHideout_2F_1R/scripts.pory"
MagmaHideout_2F_1R_EventScript_Grunt4::
# 15 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	msgbox MagmaHideout_2F_1R_Text_Grunt4PostBattle, MSGBOX_AUTOCLOSE
# 16 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	end
# 17 "data/maps/MagmaHideout_2F_1R/scripts.pory"

# 18 "data/maps/MagmaHideout_2F_1R/scripts.pory"
MagmaHideout_2F_1R_EventScript_Grunt5::
# 19 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	trainerbattle_single TRAINER_GRUNT_MAGMA_HIDEOUT_5, MagmaHideout_2F_1R_Text_Grunt5Intro, MagmaHideout_2F_1R_Text_Grunt5Defeat
# 20 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	msgbox MagmaHideout_2F_1R_Text_Grunt5PostBattle, MSGBOX_AUTOCLOSE
# 21 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	end
# 22 "data/maps/MagmaHideout_2F_1R/scripts.pory"

# 23 "data/maps/MagmaHideout_2F_1R/scripts.pory"
MagmaHideout_2F_1R_Text_Grunt14Intro:
# 24 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "Objetivo en mira.\n"
# 25 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "Protoolo de ataque activado.$"
# 26 "data/maps/MagmaHideout_2F_1R/scripts.pory"

# 27 "data/maps/MagmaHideout_2F_1R/scripts.pory"
MagmaHideout_2F_1R_Text_Grunt14Defeat:
# 28 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "N-no… Maxie…$"
# 29 "data/maps/MagmaHideout_2F_1R/scripts.pory"

# 30 "data/maps/MagmaHideout_2F_1R/scripts.pory"
MagmaHideout_2F_1R_Text_Grunt14PostBattle:
# 31 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "He fracasado.\n"
# 32 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "En alejarte a tí, y en alejar a\lesos de la División Delta.$"
# 33 "data/maps/MagmaHideout_2F_1R/scripts.pory"

# 34 "data/maps/MagmaHideout_2F_1R/scripts.pory"
MagmaHideout_2F_1R_Text_Grunt3PostBattle:
# 35 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "¡Lo logramos! ¡Estas dos!\n¡Las capturamos!\p"
# 36 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "¿Obtendremos algún aumento…?$"
# 37 "data/maps/MagmaHideout_2F_1R/scripts.pory"

# 38 "data/maps/MagmaHideout_2F_1R/scripts.pory"
MagmaHideout_2F_1R_Text_Grunt4PostBattle:
# 39 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "Ya no tengo Pokémon.\p"
# 40 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "¿Qué hacemos cuando dejen de\n"
# 41 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "hacerse las derrotadas?$"
# 42 "data/maps/MagmaHideout_2F_1R/scripts.pory"

# 43 "data/maps/MagmaHideout_2F_1R/scripts.pory"
MagmaHideout_2F_1R_Text_Grunt5Intro:
# 44 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "¡No voy a dejarte pasar!\n"
# 45 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "¡Te derrotaré!$"
# 46 "data/maps/MagmaHideout_2F_1R/scripts.pory"

# 47 "data/maps/MagmaHideout_2F_1R/scripts.pory"
MagmaHideout_2F_1R_Text_Grunt5Defeat:
# 48 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "Em…$"
# 49 "data/maps/MagmaHideout_2F_1R/scripts.pory"

# 50 "data/maps/MagmaHideout_2F_1R/scripts.pory"
MagmaHideout_2F_1R_Text_Grunt5PostBattle:
# 51 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "Bueno, está bien… Te dejo…$"
