gText_Birch_Welcome::
# 1 "data/text/birch_speech.pory"
	.string "¡Hola! Me llamo Birch.\p"
	.string "Pero todos me conocen como Profesor.\p"
	.string "$"

gText_Birch_Pokemon::
# 12 "data/text/birch_speech.pory"
	.string "\p$"

gText_Birch_MainSpeech::
# 16 "data/text/birch_speech.pory"
	.string "Me apasionan…\n"
	.string "Por eso, he dedicado mi vida a\l"
	.string "estudiarlos a fondo…\p"
	.string "¡Pero suficiente de mí!\p"
	.string "$"

gText_Birch_AndYouAre::
# 27 "data/text/birch_speech.pory"
	.string "¿A quién te pareces más?\p"
	.string "$"

gText_Birch_BoyOrGirl::
# 38 "data/text/birch_speech.pory"
	.string "¿A Brendan o May?\p"
	.string "$"

gText_Birch_WhatsYourName::
# 49 "data/text/birch_speech.pory"
	.string "¡Genial!\n"
	.string "¿Qué nombre te gustaría usar?$"

gText_Birch_SoItsPlayer::
# 60 "data/text/birch_speech.pory"
	.string "¿{PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
# 72 "data/text/birch_speech.pory"
	.string "¡Perfecto! ¡Eres {PLAYER}{KUN}, y te\n"
	.string "mudaste aquí desde Johto!\p"
	.string "$"

gText_Birch_AreYouReady::
# 83 "data/text/birch_speech.pory"
	.string "Tu propia aventura comenzará.\n"
	.string "Conocerás personas, Pokémon, e\l"
	.string "historias de lo más variadas…\p"
	.string "¡Adéntrate ahora, al Mundo Pokémon!\p"
	.string "$"

gText_Birch_YouCantBirch::
# 96 "data/text/birch_speech.pory"
	.string "N-no…\pEse… Ese es MI nombre…\pElige otro nombre.$"

gText_Birch_WaitYoureG::
# 100 "data/text/birch_speech.pory"
	.string "E-eres… ¿{PLAYER}?\p¡Genial, yo soy bi!\pPero ahora, por favor,\nescribe un nombre…\pA menos… Que quieras que\nte digan así…\p¿Quieres llamarte {PLAYER}?$"

gText_Birch_YouCantMayBoy::
# 104 "data/text/birch_speech.pory"
	.string "N-no… May es el nombre\nde MI hija…\pPor favor elije otro nombre…$"

gText_Birch_YouCantBrendanGirl::
# 108 "data/text/birch_speech.pory"
	.string "N-no… Brendan es el nombre\nde MI hijo…\pPor favor elije otro nombre…$"

gText_Birch_NotVeryOriginal::
# 112 "data/text/birch_speech.pory"
	.string "Ah, ¡{PLAYER}, entonces!\pUn nombre muy popular.\p¿{PLAYER} te parece bien?$"
