gText_Birch_Welcome::
	.string "¡Hola! Me llamo Birch.\p"
	.string "Pero todos me conocen como\n"
	.string "Profesor Pokémon, o Profe.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "unused text\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "En nuestro mundo viven los Pokémon,\n"
	.string "criaturas increíbles con poderes\l"
	.string "cuyos límites no conocemos… Me\l"
	.string "apasionan… Por eso mismo, he dedicado\l"
	.string "toda mi vida a estudiarlos a fondo…\p"
	.string "¡Pero suficiente de mí!\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "¿A quién te pareces más?\p"
	.string "$"

gText_Birch_BoyOrGirl::
	.string "¿A May, o a Brendan?$"

gText_Birch_WhatsYourName::
	.string "¡Genial!\n"
	.string "¿Qué nombre te\n"
	.string "gustaría usar?$"

gText_Birch_SoItsPlayer::
	.string "¿{PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "¡Perfecto!\p"
	.string "Eres {PLAYER}{KUN}, quien viene\n"
	.string "de Johto hasta Littleroot.\l"
	.string "$"

gText_Birch_AreYouReady::
	.string "Tu propia aventura comenzará.\n"
	.string "Conocerás personas, Pokémon,\l"
	.string "e historias de lo más variadas…\p"
	.string "¡Adéntrate ahora,\n"
	.string "al Mundo Pokémon!\p"
	.string "$"
