Unknown:
	.string "{COLOR LIGHT_GRAY}{SHADOW DARK_GRAY}???$"
Birch:
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}Profesor Birch$"
Norman:
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}Papá$"
Marta:
	.string "{COLOR LIGHT_RED}{SHADOW RED}Marta$"
Rival:
	.string "{COLOR_RIVAL}{RIVAL}$"
Roxanne:
	.string "{COLOR RED}Roxanne$"
Brawly:
	.string "{COLOR BLUE}Brawly$"
Wattson:
	.string "{COLOR BLUE}Wattson$"
Flannery:
	.string "{COLOR RED}Flannery$"
Winona:
	.string "{COLOR RED}Winona$"
Tate:
	.string "{COLOR BLUE}Tate$"
Liza:
	.string "{COLOR RED}Liza$"
Juan:
	.string "{COLOR BLUE}Juan$"
Player:
	.string "{COLOR_PLAYER}{PLAYER}$"

Archie:
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}Archie$"
	
Aqua:
	.string "{SHADOW BLUE}Recluta Aqua$"
Magma:
	.string "{SHADOW RED}Recluta Magma$"
Maxie:
	.string "{COLOR LIGHT_RED}{SHADOW RED}Maxie$"
Shelly:
	.string "{COLOR LIGHT_RED}{SHADOW RED}Shelly$"
Matt:
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}Matt$"

Courtney:
	.string "{COLOR LIGHT_RED}{SHADOW RED}Courtney$"
Tabitha:
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}Tabitha$"

Steven:
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}Steven$"
Wallace:
	.string "{COLOR LIGHT_GREEN}{SHADOW GREEN}Wallace$"

Wally:
	.string "{COLOR LIGHT_GREEN}{SHADOW GREEN}Wally$"
Phoebe:
	.string "{COLOR RED}{SHADOW LIGHT_RED}Phoebe$"
Glacia:
	.string "{COLOR RED}{SHADOW LIGHT_RED}Glacia$"
Drake:
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Drake$"
Sidney:
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Sidney$"
CampeonaLeaf:
	.string "{COLOR LIGHT_RED}{SHADOW RED}Campeona Leaf$"
Leaf:
	.string "{COLOR LIGHT_RED}{SHADOW RED}Leaf$"
PapaWally:
	.string "{COLOR BLUE}Papá de Wally$"
TioWally:
	.string "{COLOR BLUE}Tío de Wally$"
MamaWally:
	.string "{COLOR RED}Mamá de Wally$"
TiaWally:
	.string "{COLOR RED}Tía de Wally$"
Cientifico:
	.string "{COLOR BLUE}Cientifico$"
Alex:
	.string "{COLOR BLUE}Alex$"
Esmeralda:
	.string "{COLOR RED}Esmeralda$"
NoDeberiasVerlo:
	.string "No tendrías que poder ver esto.\n"
	.string "Si ves este mensaje, contacta al\l"
	.string "desarrollador y dile cómo y porqué\l"
	.string "este evento se mostró.$"
Riley:
	.string "{COLOR BLUE}Riley$"
Wanda:
	.string "{COLOR RED}Wanda$"
Camilo:
	.string "{COLOR BLUE}Camilo$"
Stern:
	.string "{COLOR BLUE}Stern$"
Briney:
	.string "{COLOR BLUE}Briney$"
Scott:
	.string "{COLOR GREEN}Scott$"
Carlos:
	.string "{COLOR BLUE}Carlos$"
RecoveredItems:
	.string "¡Has recuperado tus objetos!$"
RecoveredPokemon:
	.string "¡Has recuperado tus Pokémon!$"
RecoveredPokemonAndItems:
	.string "¡Has recuperado tus Pokémon y objetos!$"
Chico:
	.string "{COLOR BLUE}Bully$"
Gabby:
	.string "{COLOR RED}Gabby$"
Ty:
	.string "{COLOR RED}Ty$"
Delta:
	.string "{COLOR GREEN}Delta$"

