Unknown:
	.string "{COLOR LIGHT_GRAY}{SHADOW DARK_GRAY}???$"
Birch:
	.string "{COLOR LIGHT_GREEN}{SHADOW GREEN}Profe$"
Norman:
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}Papá$"
Marta:
	.string "{COLOR LIGHT_RED}{SHADOW RED}Marta$"
Rival:
	.string "{COLOR_RIVAL}{RIVAL}$"
Roxanne:
	.string "{COLOR RED}Roxanne$"
Brawly:
	.string "{COLOR BLUE}Brawly$"
Wattson:
	.string "{COLOR BLUE}Wattson$"
Flannery:
	.string "{COLOR RED}Flannery$"
Winona:
	.string "{COLOR RED}Winona$"
Tate:
	.string "{COLOR BLUE}Tate$"
Liza:
	.string "{COLOR RED}Liza$"
Juan:
	.string "{COLOR BLUE}Juan$"

Archie:
	.string "{COLOR BLUE}{SHADOW LIGHT_RED}Archie$"
	
Aqua:
	.string "{SHADOW BLUE}Soldado Aqua$"
Magma:
	.string "{SHADOW BLUE}Soldado Magma$"
Maxie:
	.string "{COLOR RED}{SHADOW BLUE}Maxie$"
Shelly:
	.string "{COLOR LIGHT_RED}{SHADOW RED}Shelly$"
Matt:
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}Matt$"

Courtney:
	.string "{COLOR LIGHT_RED}{SHADOW RED}Courtney$"
Tabitha:
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}Tabitha$"

Steven:
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}Steven$"
Wallace:
	.string "{COLOR LIGHT_GREEN}{SHADOW GREEN}Wallace$"

Wally:
	.string "{COLOR LIGHT_GREEN}{SHADOW GREEN}Wally$"
Phoebe:
	.string "{COLOR RED}{SHADOW DARK_GRAY}Phoebe$"
Glacia:
	.string "{COLOR RED}{SHADOW LIGHT_BLUE}Glacia$"
Drake:
	.string "{COLOR BLUE}{SHADOW LIGHT_RED}Drake$"
Sidney:
	.string "{COLOR BLUE}{SHADOW LIGHT_GRAY}Sidney$"
	
CampeonaLeaf:
	.string "{COLOR LIGHT_RED}{SHADOW RED}Campeona Leaf$"
Leaf:
	.string "{COLOR LIGHT_RED}{SHADOW RED}Leaf$"

PapaWally:
	.string "{COLOR BLUE}Papá de Wally$"

MamaWally:
	.string "{COLOR RED}Mamá de Wally$"

Cientifico:
	.string "{COLOR BLUE}Cientifico$"

	
