Unknown::
# 1 "data/text/name_boxes.pory"
	.string "{COLOR LIGHT_GRAY}{SHADOW DARK_GRAY}???$"

Birch::
# 4 "data/text/name_boxes.pory"
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}Profesor Birch$"

BirchEng::
# 10 "data/text/name_boxes.pory"
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}Professor Birch$"

Norman::
# 13 "data/text/name_boxes.pory"
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}Papá$"

Mama::
# 20 "data/text/name_boxes.pory"
	.string "{COLOR LIGHT_RED}{SHADOW RED}Mamá$"

Marta::
# 27 "data/text/name_boxes.pory"
	.string "{COLOR LIGHT_RED}{SHADOW RED}Marta$"

Rival::
# 30 "data/text/name_boxes.pory"
	.string "{COLOR_RIVAL}{RIVAL}$"

Roxanne::
# 33 "data/text/name_boxes.pory"
	.string "{COLOR RED}Roxanne$"

Brawly::
# 36 "data/text/name_boxes.pory"
	.string "{COLOR BLUE}Brawly$"

Wattson::
# 39 "data/text/name_boxes.pory"
	.string "{COLOR BLUE}Wattson$"

Flannery::
# 42 "data/text/name_boxes.pory"
	.string "{COLOR RED}Flannery$"

Winona::
# 45 "data/text/name_boxes.pory"
	.string "{COLOR RED}Winona$"

Tate::
# 48 "data/text/name_boxes.pory"
	.string "{COLOR BLUE}Tate$"

Liza::
# 51 "data/text/name_boxes.pory"
	.string "{COLOR RED}Liza$"

Juan::
# 54 "data/text/name_boxes.pory"
	.string "{COLOR BLUE}Juan$"

Player::
# 57 "data/text/name_boxes.pory"
	.string "{COLOR_PLAYER}{PLAYER}$"

Archie::
# 60 "data/text/name_boxes.pory"
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}Archie$"

Aqua::
# 63 "data/text/name_boxes.pory"
	.string "{SHADOW BLUE}Recluta Aqua$"

Magma::
# 69 "data/text/name_boxes.pory"
	.string "{SHADOW RED}Recluta Magma$"

Maxie::
# 75 "data/text/name_boxes.pory"
	.string "{COLOR LIGHT_RED}{SHADOW RED}Maxie$"

Shelly::
# 78 "data/text/name_boxes.pory"
	.string "{COLOR LIGHT_RED}{SHADOW RED}Shelly$"

Matt::
# 81 "data/text/name_boxes.pory"
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}Matt$"

Courtney::
# 84 "data/text/name_boxes.pory"
	.string "{COLOR LIGHT_RED}{SHADOW RED}Courtney$"

Tabitha::
# 87 "data/text/name_boxes.pory"
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}Tabitha$"

Steven::
# 90 "data/text/name_boxes.pory"
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}Steven$"

Wallace::
# 93 "data/text/name_boxes.pory"
	.string "{COLOR LIGHT_GREEN}{SHADOW GREEN}Wallace$"

Wally::
# 96 "data/text/name_boxes.pory"
	.string "{COLOR LIGHT_GREEN}{SHADOW GREEN}Wally$"

Phoebe::
# 99 "data/text/name_boxes.pory"
	.string "{COLOR RED}{SHADOW LIGHT_RED}Phoebe$"

Glacia::
# 102 "data/text/name_boxes.pory"
	.string "{COLOR RED}{SHADOW LIGHT_RED}Glacia$"

Drake::
# 105 "data/text/name_boxes.pory"
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Drake$"

Sidney::
# 108 "data/text/name_boxes.pory"
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Sidney$"

CampeonaLeaf::
# 111 "data/text/name_boxes.pory"
	.string "{COLOR LIGHT_RED}{SHADOW RED}Campeona Leaf$"

Leaf::
# 117 "data/text/name_boxes.pory"
	.string "{COLOR LIGHT_RED}{SHADOW RED}Leaf$"

PapaWally::
# 120 "data/text/name_boxes.pory"
	.string "{COLOR BLUE}Papá de Wally$"

TioWally::
# 126 "data/text/name_boxes.pory"
	.string "{COLOR BLUE}Tío de Wally$"

MamaWally::
# 132 "data/text/name_boxes.pory"
	.string "{COLOR RED}Mamá de Wally$"

TiaWally::
# 138 "data/text/name_boxes.pory"
	.string "{COLOR RED}Tía de Wally$"

Cientifico::
# 144 "data/text/name_boxes.pory"
	.string "{COLOR BLUE}Científico$"

Alex::
# 150 "data/text/name_boxes.pory"
	.string "{COLOR BLUE}Alex$"

Esmeralda::
# 153 "data/text/name_boxes.pory"
	.string "{COLOR RED}Esmeralda$"

NoDeberiasVerlo::
# 156 "data/text/name_boxes.pory"
	.string "No tendrías que poder ver esto.\n"
	.string "Si ves este mensaje, contacta al\l"
	.string "desarrollador y dile cómo y porqué\l"
	.string "este evento se mostró.$"

Riley::
# 162 "data/text/name_boxes.pory"
	.string "{COLOR BLUE}Riley$"

Wanda::
# 165 "data/text/name_boxes.pory"
	.string "{COLOR RED}Wanda$"

Camilo::
# 168 "data/text/name_boxes.pory"
	.string "{COLOR BLUE}Camilo$"

Stern::
# 171 "data/text/name_boxes.pory"
	.string "{COLOR BLUE}Stern$"

Briney::
# 174 "data/text/name_boxes.pory"
	.string "{COLOR BLUE}Briney$"

Scott::
# 177 "data/text/name_boxes.pory"
	.string "{COLOR GREEN}Scott$"

Carlos::
# 180 "data/text/name_boxes.pory"
	.string "{COLOR BLUE}Carlos$"

RecoveredItems::
# 183 "data/text/name_boxes.pory"
	.string "¡Has recuperado tus objetos!$"

RecoveredPokemon::
# 189 "data/text/name_boxes.pory"
	.string "¡Has recuperado tus Pokémon!$"

RecoveredPokemonAndItems::
# 195 "data/text/name_boxes.pory"
	.string "¡Has recuperado tus Pokémon y objetos!$"

Chico::
# 201 "data/text/name_boxes.pory"
	.string "{COLOR BLUE}Bully$"

Gabby::
# 204 "data/text/name_boxes.pory"
	.string "{COLOR RED}Gabby$"

Ty::
# 207 "data/text/name_boxes.pory"
	.string "{COLOR BLUE}Ty$"

Delta::
# 210 "data/text/name_boxes.pory"
	.string "{COLOR GREEN}Delta$"

Entrevistador::
# 213 "data/text/name_boxes.pory"
	.string "{COLOR BLUE}Entrevistador$"
