AbandonedShip_Rooms2_1F_Text_DanIntro::
# 3 "data/text/npc_dialogue.pory"
	.string "DAN: While searching for treasures,\n"
	.string "we discovered a TRAINER!$"

AbandonedShip_CaptainsOffice_Text_NoSuccessFindingScanner::
# 16 "data/text/npc_dialogue.pory"
	.string "Estoy investigando este barco\n"
	.string "en nombre del Capitán Stern.\p"
	.string "También me ha pedido que encuentre\n"
	.string "un ESCÁNER, pero no lo he visto aún…$"

AbandonedShip_CaptainsOffice_Text_OhCanYouDeliverScanner::
# 33 "data/text/npc_dialogue.pory"
	.string "¡Ahí va! ¡Eso es un ESCÁNER!\p"
	.string "Escucha, ¿puedes llevárselo\n"
	.string "tú al Capitán Stern?\p"
	.string "Todavía no he terminado\n"
	.string "de investigar el barco…$"

AbandonedShip_CaptainsOffice_Text_ThisIsSSCactus::
# 52 "data/text/npc_dialogue.pory"
	.string "Este barco se llama S.S. CACTUS.\n"
	.string "Es más antiguo que andar “palante”…$"

AbandonedShip_Corridors_1F_Text_CharlieIntro::
# 65 "data/text/npc_dialogue.pory"
	.string "¿Qué? ¿Te hace gracia que lleve\n"
	.string "flotador montado en el barco?$"

AbandonedShip_Corridors_1F_Text_CharlieDefeat::
# 78 "data/text/npc_dialogue.pory"
	.string "Vaya, me he quedado desinflado…$"

AbandonedShip_Corridors_1F_Text_CharliePostBattle::
# 89 "data/text/npc_dialogue.pory"
	.string "¡No es fácil lanzar POKé BALLS\n"
	.string "cuando llevas un flotador!$"

AbandonedShip_Corridors_1F_Text_IsntItFunHere::
# 102 "data/text/npc_dialogue.pory"
	.string "¿A que es superdivertido?\n"
	.string "¡Me lo paso pipa aquí!$"

AbandonedShip_Corridors_B1F_Text_DuncanIntro::
# 115 "data/text/npc_dialogue.pory"
	.string "Cuando salimos al mar, los MARINEROS\n"
	.string "siempre llevamos nuestros POKéMON.\l"
	.string "¿Te hace un combatito?$"

AbandonedShip_Corridors_B1F_Text_DuncanDefeat::
# 130 "data/text/npc_dialogue.pory"
	.string "Huy, ¡tocado y hundido!$"

AbandonedShip_Corridors_B1F_Text_DuncanPostBattle::
# 141 "data/text/npc_dialogue.pory"
	.string "El barco está casi tocando fondo.\p"
	.string "Si un POKéMON supiera bucear,\n"
	.string "quizás podríamos avanzar…$"

AbandonedShip_Corridors_B1F_Text_YayItsAShip::
# 157 "data/text/npc_dialogue.pory"
	.string "Las profundidades del océano y de la\n"
	.string "arrogancia de Devon me lo han\l"
	.string "arrebatado todo.\p"
	.string "Mi familia, mis esperanzas, e incluso mi\n"
	.string "propia infancia.\p"
	.string "108 años pasarán, y aún mi alma este\n"
	.string "lugar va a rondar.$"

AbandonedShip_Corridors_B1F_Text_DoorIsLocked::
# 170 "data/text/npc_dialogue.pory"
	.string "La puerta está cerrada.\p"
	.string "En la puerta pone “ALMACÉN”.$"

AbandonedShip_Corridors_B1F_Text_InsertedStorageKey::
# 183 "data/text/npc_dialogue.pory"
	.string "{PLAYER} ha metido la LLAVE ALMACÉN\n"
	.string "y la ha hecho girar.\p"
	.string "La LLAVE se ha quedado atascada,\n"
	.string "pero la puerta se ha abierto.$"

AbandonedShip_Text_TheDoorIsOpen::
# 200 "data/text/npc_dialogue.pory"
	.string "La puerta está abierta.$"

AbandonedShip_HiddenFloorCorridors_Text_Rm1DoorIsLocked::
# 212 "data/text/npc_dialogue.pory"
	.string "La puerta está cerrada.\p"
	.string "En la puerta pone “CABINA 1”.$"

AbandonedShip_HiddenFloorCorridors_Text_Rm2DoorIsLocked::
# 225 "data/text/npc_dialogue.pory"
	.string "La puerta está cerrada.\p"
	.string "En la puerta pone “CABINA 2”.$"

AbandonedShip_HiddenFloorCorridors_Text_Rm4DoorIsLocked::
# 238 "data/text/npc_dialogue.pory"
	.string "La puerta está cerrada.\p"
	.string "En la puerta pone “CABINA 4”.$"

AbandonedShip_HiddenFloorCorridors_Text_Rm6DoorIsLocked::
# 251 "data/text/npc_dialogue.pory"
	.string "La puerta está cerrada.\p"
	.string "En la puerta pone “CABINA 6”.$"

AbandonedShip_HiddenFloorCorridors_Text_InsertedKey::
# 264 "data/text/npc_dialogue.pory"
	.string "{PLAYER} ha metido la LLAVE\n"
	.string "y la ha hecho girar.\p"
	.string "La LLAVE se ha quedado atascada,\n"
	.string "pero la puerta se ha abierto.$"

AbandonedShip_HiddenFloorRooms_Text_BrightShinyTrash::
# 283 "data/text/npc_dialogue.pory"
	.string "¡Brilla un montón!\n"
	.string "Pero es basura… Se parece bastante a\l"
	.string "Pokémon Diamante y Perla.$"

DewfordTown_Text_BrineyLandedInSlateportDeliverGoods::
# 300 "data/text/npc_dialogue.pory"
	.string "¡Eh, grumete!\n"
	.string "¡Hemos arribado a CIUDAD PORTUAL!\p"
	.string "Supongo que vas a visitar al CAP.\n"
	.string "BABOR y entregar las PIEZAS DEVON,\l"
	.string "¿no es así?$"

Route109_Text_BrineySailToDewfordQuestion::
# 318 "data/text/npc_dialogue.pory"
	.string "¿No vas a entregar\n"
	.string "las PIEZAS DEVON?\p"
	.string "¿Quieres volver a AZULIZA?$"

Route109_Text_BrineyDewfordItIs::
# 334 "data/text/npc_dialogue.pory"
	.string "¡Pues rumbo a AZULIZA!\p"
	.string "¡Levad anclas!\n"
	.string "¡PEEKO, bonito, nos vamos!$"

Route109_Text_BrineyDeliverDevonGoods::
# 349 "data/text/npc_dialogue.pory"
	.string "Pues ve a entregar\n"
	.string "las PIEZAS DEVON. Yo te espero.$"

DewfordTown_Text_BrineyLandedInSlateport::
# 362 "data/text/npc_dialogue.pory"
	.string "¡Eh, grumete!\n"
	.string "¡Hemos arribado a CIUDAD PORTUAL!\p"
	.string "Cuando quieras volver a hacerte\n"
	.string "a la mar, me lo dices, ¿eh?$"

Route109_Text_BrineyWhereAreWeBound::
# 379 "data/text/npc_dialogue.pory"
	.string "¡Eh, grumete!\n"
	.string "¡Yo levo anclas cuando quieras!\p"
	.string "Venga, ¿adónde vamos?$"

Route109_Text_BrineyTellMeWhenYouNeedToSail::
# 397 "data/text/npc_dialogue.pory"
	.string "Cuando quieras volver\n"
	.string "a hacerte a la mar, llámame.$"

Route109_Text_ChillAtMyPapasSpot::
# 410 "data/text/npc_dialogue.pory"
	.string "¡Entrenadores, aquí!\n"
	.string "Ya sean ardientes cual fuego,\l"
	.string "o se le den bien cualquier juego,\l"
	.string "¡mi papá les romperá los huevos!$"

Route109_Text_LittleKidsDartAround::
# 427 "data/text/npc_dialogue.pory"
	.string "Los niños pueden perderse de vista\n"
	.string "en un segundo…\p"
	.string "Tienes que estar siempre pendiente\n"
	.string "de ellos. Es agotador.\p"
	.string "El mío está con mi POKéMON, así\n"
	.string "que debe de estar bien…$"

Route109_Text_SandCastleTakingLongTime::
# 447 "data/text/npc_dialogue.pory"
	.string "Estamos… tardando un montón… en\n"
	.string "terminar nuestro… castillo de arena…\p"
	.string "………… ………… ………… …………$"

Route109_Text_YouCanHaveThis::
# 460 "data/text/npc_dialogue.pory"
	.string "¡Toma esto para ti!$"

Route109_Text_WereGoingToMakeBigCastle::
# 471 "data/text/npc_dialogue.pory"
	.string "Usaremos… toda la arena para este…\n"
	.string "castillo de arena…\p"
	.string "Tú serás… nuestra servidumbre…$"

Route109_Text_ZigzagoonPicksUpLitter::
# 482 "data/text/npc_dialogue.pory"
	.string "El agua de esta zona está limpia.\p"
	.string "Pero, a veces, mi ZIGZAGOON recoge\n"
	.string "basura en la orilla…\p"
	.string "Cuando el agua sucia se evapora, cae en\n"
	.string "forma de lluvia y va a parar a los ríos,\l"
	.string "de los que se saca el agua potable.\p"
	.string "Si contaminamos el mar, acabamos\n"
	.string "pagando el pato nosotros.$"

Route109_Text_ZigzagoonCry::
# 506 "data/text/npc_dialogue.pory"
	.string "ZIGZAGOON: ¿Zigzaaa? :($"

Route109_Text_SeashoreHouseSign::
# 517 "data/text/npc_dialogue.pory"
	.string "CASA de la PLAYA\p"
	.string "“¡Combates al rojo vivo!\n"
	.string "¡Sólo para ENTRENADORES apasionados!”$"

Route109_Text_TrainerTipsSign::
# 532 "data/text/npc_dialogue.pory"
	.string "PISTAS para ENTRENADORES\p"
	.string "POKéMON que tienen el mismo nivel\n"
	.string "pueden tener distintas habilidades.\p"
	.string "Dicen que los POKéMON entrenados por\n"
	.string "ENTRENADORES se vuelven más fuertes\l"
	.string "que los POKéMON salvajes.$"

AbandonedShip_Rooms2_1F_Text_DanDefeat::
# 552 "data/text/npc_dialogue.pory"
	.string "DAN: We couldn't win even though\n"
	.string "we worked together…$"

AbandonedShip_Rooms2_1F_Text_DanPostBattle::
# 557 "data/text/npc_dialogue.pory"
	.string "DAN: We can't find any treasures…\n"
	.string "I wonder if someone got them already?$"

AbandonedShip_Rooms2_1F_Text_DanNotEnoughMons::
# 562 "data/text/npc_dialogue.pory"
	.string "DAN: You don't even have two POKéMON.\n"
	.string "You can't expect to beat us like that.$"

AbandonedShip_Rooms2_1F_Text_KiraIntro::
# 567 "data/text/npc_dialogue.pory"
	.string "KIRA: Oh?\n"
	.string "We were searching for treasures.\l"
	.string "But we discovered a TRAINER instead!$"

AbandonedShip_Rooms2_1F_Text_KiraDefeat::
# 573 "data/text/npc_dialogue.pory"
	.string "KIRA: Ooh, so strong!$"

AbandonedShip_Rooms2_1F_Text_KiraPostBattle::
# 577 "data/text/npc_dialogue.pory"
	.string "KIRA: Where could the treasures be?\p"
	.string "I've already decided what I'm buying\n"
	.string "when we find the treasures!$"

AbandonedShip_Rooms2_1F_Text_KiraNotEnoughMons::
# 583 "data/text/npc_dialogue.pory"
	.string "KIRA: Oh, you don't have two POKéMON?\n"
	.string "We'll have to battle some other time!$"

AbandonedShip_Rooms2_1F_Text_KiraRegister::
# 588 "data/text/npc_dialogue.pory"
	.string "KIRA: Oh, you make me so angry!\n"
	.string "I'm going to register you for that!$"

AbandonedShip_Rooms2_1F_Text_DanRematchIntro::
# 593 "data/text/npc_dialogue.pory"
	.string "DAN: We've been searching for\n"
	.string "treasures all this time.\p"
	.string "Our POKéMON have grown stronger, too.\n"
	.string "Let us show you, okay?$"

AbandonedShip_Rooms2_1F_Text_DanRematchDefeat::
# 600 "data/text/npc_dialogue.pory"
	.string "DAN: You're strong, as usual!$"

AbandonedShip_Rooms2_1F_Text_DanPostRematch::
# 604 "data/text/npc_dialogue.pory"
	.string "DAN: We can't find any treasures,\n"
	.string "we lose at POKéMON…\p"
	.string "I want to go home… But if I say that,\n"
	.string "she gets all angry with me…$"

AbandonedShip_Rooms2_1F_Text_DanRematchNotEnoughMons::
# 611 "data/text/npc_dialogue.pory"
	.string "DAN: You don't even have two POKéMON.\n"
	.string "You can't expect to beat us like that.$"

AbandonedShip_Rooms2_1F_Text_KiraRematchIntro::
# 616 "data/text/npc_dialogue.pory"
	.string "KIRA: Oh? We meet again!\p"
	.string "Just like us, you still haven't given up\n"
	.string "searching for treasures, have you?\p"
	.string "Want to make it so the loser has\n"
	.string "to give up searching?$"

AbandonedShip_Rooms2_1F_Text_KiraRematchDefeat::
# 624 "data/text/npc_dialogue.pory"
	.string "KIRA: Oh, we lost again…$"

AbandonedShip_Rooms2_1F_Text_KiraPostRematch::
# 628 "data/text/npc_dialogue.pory"
	.string "KIRA: We're not leaving until we raise\n"
	.string "our POKéMON some more and we find\l"
	.string "the treasures here!$"

AbandonedShip_Rooms2_1F_Text_KiraRematchNotEnoughMons::
# 634 "data/text/npc_dialogue.pory"
	.string "KIRA: Oh, you don't have two POKéMON?\n"
	.string "We'll have to battle some other time!$"

AbandonedShip_Rooms2_1F_Text_JaniIntro::
# 639 "data/text/npc_dialogue.pory"
	.string "I'm not good at swimming,\n"
	.string "but I am good at battles!$"

AbandonedShip_Rooms2_1F_Text_JaniDefeat::
# 644 "data/text/npc_dialogue.pory"
	.string "Oops.\n"
	.string "That didn't go very well.$"

AbandonedShip_Rooms2_1F_Text_JaniPostBattle::
# 649 "data/text/npc_dialogue.pory"
	.string "Walking around barefoot in this ship\n"
	.string "is kind of gross.$"

AbandonedShip_Rooms2_1F_Text_GarrisonIntro::
# 654 "data/text/npc_dialogue.pory"
	.string "Strength and compassion…\n"
	.string "Those are a TRAINER's treasures!$"

AbandonedShip_Rooms2_1F_Text_GarrisonDefeat::
# 659 "data/text/npc_dialogue.pory"
	.string "Ah, there is something about you\n"
	.string "that sparkles.$"

AbandonedShip_Rooms2_1F_Text_GarrisonPostBattle::
# 664 "data/text/npc_dialogue.pory"
	.string "In a cabin somewhere on board,\n"
	.string "I saw something sparkle.$"
