gText_ObtainedTheItem::
# 1 "data/text/obtain_item.pory"
	.string "¡Obtuviste una unidad de\n"
	.string "{STR_VAR_2}!$"

gText_TheBagIsFull::
# 13 "data/text/obtain_item.pory"
	.string "La Mochila está llena…$"

gText_PutItemInPocket::
# 24 "data/text/obtain_item.pory"
	.string "{PLAYER} puso {STR_VAR_2} en el\n"
	.string "bolsillo {STR_VAR_3}.$"

gText_PlayerFoundOneItem::
# 35 "data/text/obtain_item.pory"
	.string "¡{PLAYER} encontró una unidad de\n"
	.string "{STR_VAR_2}!$"

gText_TooBadBagIsFull::
# 46 "data/text/obtain_item.pory"
	.string "¡Qué mal! La Mochila está llena…$"

gText_PlayerPutItemInBag::
# 57 "data/text/obtain_item.pory"
	.string "{PLAYER} guardó {STR_VAR_2} en la\n"
	.string "Mochila.$"

gText_ObtainedTheDecor::
# 68 "data/text/obtain_item.pory"
	.string "¡Conseguiste una unidad de\n"
	.string "{STR_VAR_2}!$"

gText_NoRoomLeftForAnother::
# 79 "data/text/obtain_item.pory"
	.string "¡Pero ya no hay espacio para más\n"
	.string "{STR_VAR_2}!$"

gText_TheDecorWasTransferredToThePC::
# 90 "data/text/obtain_item.pory"
	.string "¡{STR_VAR_2} fue transferido al PC!$"
