gText_WouldYouLikeToRestYourPkmn::
    .string "¡Bienvenid{OA} al\n"
    .string "Centro Pokémon!\p"
    .string "Restauraré la salud de\n"
	.string "tus Pokémon.$"

gText_IllTakeYourPkmn::
    .string "Los cuidaré muy bien.$"

gText_RestoredPkmnToFullHealth::
    .string "¡Tus Pokémon están\n"
    .string "felices y curados!$"

gText_WeHopeToSeeYouAgain::
    .string "¡Buena suerte!$"

gText_WelcomeCutShort::
    .string "¡Bienvenid{OA} al\n"
    .string "Centro Pokémon!\p"
    .string "Restauraré la salud…$"

gText_NoticesGoldCard::
	.string "Es-esa tarjeta…\n"
	.string "¿Será…? ¡¿LA TARJETA DE ORO?!\p"
	.string "¡OH, ES ORO AUTÉNTICO!\n"
	.string "¡LAS ESTRELLAS RESPLANDECEN!\p"
	.string "He visto tantos Entrenadores con\n"
	.string "Tarjetas de Plata, pero, {PLAYER},\l"
	.string "¡Nunca vi a nadie con una de Oro! ¡Creí\l"
	.string "que eran sólo una leyenda!\p"
	.string "Bien, {PLAYER}, por favor, concédeme\n"
	.string "el honor de curar a tu maravilloso\l"
	.string "equipo…$"

gText_YouWantTheUsual::
	.string "¡Feliz de verte otra vez, {PLAYER}!\n"
	.string "¿Lo de siempre, me imagino?$"

gText_IllTakeYourPkmn2::
    .string "No me tardo.$"

gText_ThankYouForWaiting::
    .string "¡Muchísimas gracia!$"

gText_WeHopeToSeeYouAgain2::
    .string "¡Sigue siendo maravillos{OA}!$"