PetalburgCity_House2_MapScripts::
	.byte 0

PetalburgCity_House2_EventScript_Woman::
	msgbox PetalburgCity_House2_Text_NormanBecameGymLeader, MSGBOX_NPC
	end

PetalburgCity_House2_EventScript_SchoolKid::
	msgbox PetalburgCity_House2_Text_BattledNormanOnce, MSGBOX_NPC
	end

PetalburgCity_House2_Text_NormanBecameGymLeader:
	.string "Norman ha sido nuestro Líder de\n"
	.string "Gimnasio por poco tiempo, y aunque\l"
	.string "haya acabado de mudarse hace poco, ya\l"
	.string "entró en una racha ganadora…$"

PetalburgCity_House2_Text_BattledNormanOnce:
	.string "Intenté enfrentarme a Norman con mis\n"
	.string "Pokémon Tipo Acero, pero…\p"
	.string "Él era tan… Y, y, eso me distrajo… Y sus\n"
	.string "brazos y, y…\p"
	.string "Aunque sin contar eso, creo que perdí\n"
	.string "porque tenía dos Magnemite nivel 13……$"

