# 1 "data/maps/PetalburgCity_House2/scripts.pory"

# 2 "data/maps/PetalburgCity_House2/scripts.pory"
PetalburgCity_House2_MapScripts::
# 3 "data/maps/PetalburgCity_House2/scripts.pory"
	.byte 0
# 4 "data/maps/PetalburgCity_House2/scripts.pory"

# 5 "data/maps/PetalburgCity_House2/scripts.pory"
PetalburgCity_House2_EventScript_Woman::
# 6 "data/maps/PetalburgCity_House2/scripts.pory"
	msgbox PetalburgCity_House2_Text_NormanBecameGymLeader, MSGBOX_NPC
# 7 "data/maps/PetalburgCity_House2/scripts.pory"
	end
# 8 "data/maps/PetalburgCity_House2/scripts.pory"

# 9 "data/maps/PetalburgCity_House2/scripts.pory"
PetalburgCity_House2_EventScript_SchoolKid::
# 10 "data/maps/PetalburgCity_House2/scripts.pory"
	msgbox PetalburgCity_House2_Text_BattledNormanOnce, MSGBOX_NPC
# 11 "data/maps/PetalburgCity_House2/scripts.pory"
	end
# 12 "data/maps/PetalburgCity_House2/scripts.pory"

# 13 "data/maps/PetalburgCity_House2/scripts.pory"
PetalburgCity_House2_Text_NormanBecameGymLeader:
# 14 "data/maps/PetalburgCity_House2/scripts.pory"
	.string "Norman ha sido nuestro Líder de\n"
# 15 "data/maps/PetalburgCity_House2/scripts.pory"
	.string "Gimnasio por poco tiempo, y aunque\l"
# 16 "data/maps/PetalburgCity_House2/scripts.pory"
	.string "haya acabado de mudarse hace poco, ya\l"
# 17 "data/maps/PetalburgCity_House2/scripts.pory"
	.string "entró en una racha ganadora…$"
# 18 "data/maps/PetalburgCity_House2/scripts.pory"

# 19 "data/maps/PetalburgCity_House2/scripts.pory"
PetalburgCity_House2_Text_BattledNormanOnce:
# 20 "data/maps/PetalburgCity_House2/scripts.pory"
	.string "Intenté enfrentarme a Norman con mis\n"
# 21 "data/maps/PetalburgCity_House2/scripts.pory"
	.string "Pokémon Tipo Acero, pero…\p"
# 22 "data/maps/PetalburgCity_House2/scripts.pory"
	.string "Él era tan… Y, y, eso me distrajo… Y sus\n"
# 23 "data/maps/PetalburgCity_House2/scripts.pory"
	.string "brazos y, y…\p"
# 24 "data/maps/PetalburgCity_House2/scripts.pory"
	.string "Aunque sin contar eso, creo que perdí\n"
# 25 "data/maps/PetalburgCity_House2/scripts.pory"
	.string "porque tenía dos Magnemite nivel 13……$"
