# 1 "data/maps/OldaleTown_House1/scripts.pory"

# 2 "data/maps/OldaleTown_House1/scripts.pory"
OldaleTown_House1_MapScripts::
# 3 "data/maps/OldaleTown_House1/scripts.pory"
	.byte 0
# 4 "data/maps/OldaleTown_House1/scripts.pory"

# 5 "data/maps/OldaleTown_House1/scripts.pory"
OldaleTown_House1_EventScript_Woman::
# 6 "data/maps/OldaleTown_House1/scripts.pory"
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
# 7 "data/maps/OldaleTown_House1/scripts.pory"
	end
# 8 "data/maps/OldaleTown_House1/scripts.pory"

# 9 "data/maps/OldaleTown_House1/scripts.pory"
OldaleTown_House1_Text_LeftPokemonGoesOutFirst:
# 10 "data/maps/OldaleTown_House1/scripts.pory"
	.string "Cuando un Pokémon tiene equipado el\n"
# 11 "data/maps/OldaleTown_House1/scripts.pory"
	.string "Repartir Experiencia, recibirá\l"
# 12 "data/maps/OldaleTown_House1/scripts.pory"
	.string "el {COLOR BLUE}triple de puntos de experiencia{COLOR DARK_GRAY}\l"
# 13 "data/maps/OldaleTown_House1/scripts.pory"
	.string "que recibiría normalmente, esto\l"
# 14 "data/maps/OldaleTown_House1/scripts.pory"
	.string "para entrenarlo más rápidamente.\p"
# 15 "data/maps/OldaleTown_House1/scripts.pory"
	.string "Aunque no sé dónde se consigue eso.$"
