PetalburgCity_House1_MapScripts::
	.byte 0

PetalburgCity_House1_EventScript_Man::
	msgbox PetalburgCity_House1_Text_TravelingIsWonderful, MSGBOX_NPC
	end

PetalburgCity_House1_EventScript_Woman::
	msgbox PetalburgCity_House1_Text_GoOnAdventure, MSGBOX_NPC
	end

PetalburgCity_House1_Text_TravelingIsWonderful:
	.string "¡Viajar es increíble!\p"
	.string "Sentir el viento en mi pelo, acompañar a\n"
	.string "mis Pokémon y mis amigos, ¡Viajar lo era\l"
	.string "todo para mí!\p"
	.string "Pero mi familia me importa mucho más\n"
	.string "ahora.$"

PetalburgCity_House1_Text_GoOnAdventure:
	.string "No sé qué hacer, quiero ir de viaje, pero\n"
	.string "también quiero quedarme…\p"
	.string "-suspiro- También me gustaría tener\n"
	.string "amigos nuevos, quizá un novio o novia,\l"
	.string "viajar por todo el mundo junto a todos\l"
	.string "mis Pokémon…$"
