# 1 "data/maps/PetalburgCity_House1/scripts.pory"

# 2 "data/maps/PetalburgCity_House1/scripts.pory"
PetalburgCity_House1_MapScripts::
# 3 "data/maps/PetalburgCity_House1/scripts.pory"
	.byte 0
# 4 "data/maps/PetalburgCity_House1/scripts.pory"

# 5 "data/maps/PetalburgCity_House1/scripts.pory"
PetalburgCity_House1_EventScript_Man::
# 6 "data/maps/PetalburgCity_House1/scripts.pory"
	msgbox PetalburgCity_House1_Text_TravelingIsWonderful, MSGBOX_NPC
# 7 "data/maps/PetalburgCity_House1/scripts.pory"
	end
# 8 "data/maps/PetalburgCity_House1/scripts.pory"

# 9 "data/maps/PetalburgCity_House1/scripts.pory"
PetalburgCity_House1_EventScript_Woman::
# 10 "data/maps/PetalburgCity_House1/scripts.pory"
	msgbox PetalburgCity_House1_Text_GoOnAdventure, MSGBOX_NPC
# 11 "data/maps/PetalburgCity_House1/scripts.pory"
	end
# 12 "data/maps/PetalburgCity_House1/scripts.pory"

# 13 "data/maps/PetalburgCity_House1/scripts.pory"
PetalburgCity_House1_Text_TravelingIsWonderful:
# 14 "data/maps/PetalburgCity_House1/scripts.pory"
	.string "¡Viajar es increíble!\p"
# 15 "data/maps/PetalburgCity_House1/scripts.pory"
	.string "Sentir el viento en mi pelo, acompañar a\n"
# 16 "data/maps/PetalburgCity_House1/scripts.pory"
	.string "mis Pokémon y mis amigos, ¡Viajar lo era\l"
# 17 "data/maps/PetalburgCity_House1/scripts.pory"
	.string "todo para mí!\p"
# 18 "data/maps/PetalburgCity_House1/scripts.pory"
	.string "Pero mi familia me importa mucho más\n"
# 19 "data/maps/PetalburgCity_House1/scripts.pory"
	.string "ahora.$"
# 20 "data/maps/PetalburgCity_House1/scripts.pory"

# 21 "data/maps/PetalburgCity_House1/scripts.pory"
PetalburgCity_House1_Text_GoOnAdventure:
# 22 "data/maps/PetalburgCity_House1/scripts.pory"
	.string "No sé qué hacer, quiero ir de viaje, pero\n"
# 23 "data/maps/PetalburgCity_House1/scripts.pory"
	.string "también quiero quedarme…\p"
# 24 "data/maps/PetalburgCity_House1/scripts.pory"
	.string "-suspiro- También me gustaría tener\n"
# 25 "data/maps/PetalburgCity_House1/scripts.pory"
	.string "amigos nuevos, quizá un novio o novia,\l"
# 26 "data/maps/PetalburgCity_House1/scripts.pory"
	.string "viajar por todo el mundo junto a todos\l"
# 27 "data/maps/PetalburgCity_House1/scripts.pory"
	.string "mis Pokémon…$"
