.set LOCALID_TWIN, 2
.set LOCALID_BULLY_1, 3
.set LOCALID_BULLY_2, 4
.set LOCALID_WALLY, 5

VerdanturfTown_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, VerdanturfTown_OnTransition
	map_script MAP_SCRIPT_ON_FRAME_TABLE, VerdanturfTown_OnFrame
	.byte 0

VerdanturfTown_OnTransition:
	setflag FLAG_VISITED_VERDANTURF_TOWN
	setvar VAR_CONTEST_HALL_STATE, 0
	call_if_eq VAR_VERDANTURF_TOWN_STATE, 1, VerdanturfTown_OnTransition_SetTint
	end

VerdanturfTown_OnFrame:
	map_script_2 VAR_VERDANTURF_TOWN_STATE, 1, VerdanturfTown_EventScript_WallysMemory
	.2byte 0

VerdanturfTown_OnTransition_SetTint:
	setflag FLAG_HIDE_MAP_NAME_POPUP
	call Script_SetSepiaTint
	savebgm MUS_END
	return

VerdanturfTown_EventScript_WallysMemory:
	lockall
	special SpawnCameraObject
	setobjectxy LOCALID_BULLY_1, 13, 7
	setobjectxy LOCALID_BULLY_2, 12, 8
	applymovement LOCALID_BULLY_1, Common_Movement_FaceDown
	applymovement LOCALID_BULLY_2, Common_Movement_FaceRight
	waitmovement 0
	fadescreen FADE_FROM_BLACK
	delay 16
	opendoor 10, 14
	waitdooranim
	addobject LOCALID_WALLY
	applymovement LOCALID_WALLY, VerdanturfTown_Movement_WallyShopping1
	waitmovement 0
	closedoor 10, 14
	waitdooranim
	applymovement LOCALID_WALLY, VerdanturfTown_Movement_WallyShopping2
	applymovement OBJ_EVENT_ID_CAMERA, VerdanturfTown_Movement_WallyShopping2
	namebox Wally
	msgbox VerdanturfTown_Text_WallyExplains1, MSGBOX_DEFAULT
	hidenamebox
	closemessage
	waitmovement 0
	applymovement LOCALID_BULLY_1, VerdanturfTown_Movement_AttackWally
	applymovement LOCALID_WALLY, VerdanturfTown_Movement_WallyPushed
	applymovement OBJ_EVENT_ID_CAMERA, VerdanturfTown_Movement_CameraDown
	waitmovement 0
	setvar VAR_VERDANTURF_TOWN_STATE, 2
	special RemoveCameraObject
	setflag FLAG_HIDE_WALLY_VERDANTURF
	setflag FLAG_REMOVE_WARP_FADE_OUT
	switch VAR_0x8004
	case DIR_EAST, VerdanturfTown_EventScript_WallysMemoryEast
	case DIR_NORTH, VerdanturfTown_EventScript_WallysMemoryNorth
	case DIR_WEST, VerdanturfTown_EventScript_WallysMemoryWest
	case DIR_SOUTH, VerdanturfTown_EventScript_WallysMemorySouth
	release
	end

VerdanturfTown_EventScript_WallysMemoryEast::
	warp MAP_DEWFORD_TOWN, 5, 18
	release
	end

VerdanturfTown_EventScript_WallysMemoryNorth::
	warp MAP_DEWFORD_TOWN, 6, 19
	release
	end

VerdanturfTown_EventScript_WallysMemoryWest::
	warp MAP_DEWFORD_TOWN, 7, 18
	release
	end

VerdanturfTown_EventScript_WallysMemorySouth::
	warp MAP_DEWFORD_TOWN, 6, 17
	release
	end

VerdanturfTown_Movement_WallyShopping1:
	walk_down
	delay_16
	walk_in_place_up
	step_end

VerdanturfTown_Movement_WallyShopping2:
	walk_down
	walk_right
	walk_right
	walk_right
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	delay_16
	walk_in_place_left
	delay_16
	walk_in_place_up
	step_end

VerdanturfTown_Movement_AttackWally:
	walk_fast_down
	delay_16
	delay_8
	walk_fast_down
	step_end

VerdanturfTown_Movement_WallyPushed:
	lock_facing_direction
	delay_8
	jump_down
	delay_16
	jump_down
	step_end

VerdanturfTown_Movement_CameraDown:
	delay_8
	walk_down
	delay_16
	walk_down
	step_end

VerdanturfTown_Text_WallyExplains1:
	.string "Y cuando vivía en Verdanturf, las cosas\n"
	.string "no eran nada diferentes.\p"
	.string "Recuerdo que varias veces, al querer ir\n"
	.string "a comprar cosas en el Centro Pokémon,\l"
	.string "me molestaban unos de mis vecinos,\l"
	.string "diciéndome cosas horribles y no\l"
	.string "dejándome continuar...$"

VerdanturfTown_EventScript_Twin::
	lock
	faceplayer
	goto_if_set FLAG_RUSTURF_TUNNEL_OPENED, VerdanturfTown_EventScript_TwinTunnelOpen
	msgbox VerdanturfTown_Text_ManTryingToDigTunnel, MSGBOX_DEFAULT
	applymovement LOCALID_TWIN, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

VerdanturfTown_EventScript_TwinTunnelOpen::
	msgbox VerdanturfTown_Text_ManDugTunnelForLove, MSGBOX_DEFAULT
	applymovement LOCALID_TWIN, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

VerdanturfTown_EventScript_Man::
	msgbox VerdanturfTown_Text_AirCleanHere, MSGBOX_NPC
	end

VerdanturfTown_EventScript_Camper::
	msgbox VerdanturfTown_Text_MakeBattleTentDebut, MSGBOX_NPC
	end

VerdanturfTown_EventScript_Boy::
	lock
	faceplayer
	goto_if_set FLAG_RUSTURF_TUNNEL_OPENED, VerdanturfTown_EventScript_BoyTunnelOpen
	msgbox VerdanturfTown_Text_GuyTryingToBustThroughCave, MSGBOX_DEFAULT
	release
	end

VerdanturfTown_EventScript_BoyTunnelOpen::
	msgbox VerdanturfTown_Text_EasyToGetToRustboroNow, MSGBOX_DEFAULT
	release
	end

VerdanturfTown_EventScript_TownSign::
	msgbox VerdanturfTown_Text_TownSign, MSGBOX_SIGN
	end

VerdanturfTown_EventScript_WandasHouseSign::
	msgbox VerdanturfTown_Text_WandasHouse, MSGBOX_SIGN
	end

VerdanturfTown_EventScript_BattleTentSign::
	msgbox VerdanturfTown_Text_BattleTentSign, MSGBOX_SIGN
	end

VerdanturfTown_EventScript_RusturfTunnelSign::
	msgbox VerdanturfTown_Text_RusturfTunnelSign, MSGBOX_SIGN
	end

VerdanturfTown_Text_ManTryingToDigTunnel:
	.string "My papa told me.\p"
	.string "He says this tunnel is full of\n"
	.string "timid POKéMON.\p"
	.string "They get all scared of loud noise and\n"
	.string "make a big uproar.\p"
	.string "So they had to stop the big tunnel\n"
	.string "project.\p"
	.string "But there's one man. He's trying to dig\n"
	.string "the tunnel by himself!$"

VerdanturfTown_Text_ManDugTunnelForLove:
	.string "There was a man who dug a tunnel for\n"
	.string "a lady he loved.\p"
	.string "I don't really get it, but hey!$"

VerdanturfTown_Text_AirCleanHere:
	.string "The way the winds blow, volcanic ash\n"
	.string "is never blown in this direction.\p"
	.string "The air is clean and delicious here.\n"
	.string "Living here should do wonders for even\l"
	.string "frail and sickly people.$"

VerdanturfTown_Text_MakeBattleTentDebut:
	.string "My POKéMON and I, we've been riding\n"
	.string "a hot winning streak.\p"
	.string "So I decided to make my BATTLE TENT\n"
	.string "debut in this town.$"

VerdanturfTown_Text_GuyTryingToBustThroughCave:
	.string "Did you see the cave next to the\n"
	.string "POKéMON MART?\p"
	.string "There's a guy in there who's trying to\n"
	.string "bust up boulders so he can bust out\l"
	.string "through to the other side.\p"
	.string "It'd be great if we could go through…\n"
	.string "It'll make it easy to visit RUSTBORO.$"

VerdanturfTown_Text_EasyToGetToRustboroNow:
	.string "That cave next to the POKéMON MART\n"
	.string "is now a tunnel to the other side.\p"
	.string "It's great--it's easy to go shop for\n"
	.string "new DEVON products in RUSTBORO now.$"

VerdanturfTown_Text_TownSign:
	.string "VERDANTURF TOWN\p"
	.string "“The windswept highlands with the\n"
	.string "sweet fragrance of grass.”$"

VerdanturfTown_Text_WandasHouse:
	.string "WANDA'S HOUSE$"

VerdanturfTown_Text_BattleTentSign:
	.string "BATTLE TENT VERDANTURF SITE\n"
	.string "“Feast Your Eyes on Battles!”$"

VerdanturfTown_Text_RusturfTunnelSign:
	.string "RUSTURF TUNNEL\n"
	.string "“Linking RUSTBORO and VERDANTURF\p"
	.string "“The tunnel project has been\n"
	.string "canceled.”$"
